ex2/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static 

from facex.views import iv 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('facex/', include('facex.urls')),
    path('users/',include('users_app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns+=[
	path('favicon.ico/',iv,name= 'fav')
]

facex/urls.py
from django.urls import path
from .views import *

app_name = 'facex'

urlpatterns = [
	path('', my_home ,name='my_home'),
	path('base/', base, name='base'),
	path('home2/', my_home2, name='my_home2'),
	path('home3/', my_home3, name='my_home3'),
	path('index/',index, name='index'),
	path('register/',register_user, name='register'),
	path('login/', login, name='login'),
	path('form/', form_view, name='form'),
]

users_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
	path('home/',views.home, name = 'home'),
]

facex/models.py
from django.db import models



from django.db import models


cafe_choice = [
	('C','Cafe'),
	('NC','None Cafe')
]

region_choice = [
	('AA', 'Addis Ababa'),
	('AF','Afar'),
	('AM','Amhara'),
	('BN','Benishangul-Gumuz'),
	('DD','Dire Dawa'),
	('GM','Gambela'),
	('HR','Harari'),
	('Or','Oromiya'),
	('SD','Sidama'),
	('SNNP','Southern Nations, Nationalities, and Peoples'),
	('TG','Tigray'),
]


sex_choice = [
	('M','Male'),
	('F','Female'),

]



class Department(models.Model):
	department = models.CharField(max_length = 200)

	def __str__(self):
		return self.department

class FieldOfStudy(models.Model):
	field_of_study = models.CharField(max_length = 200)

	def __str__(self):
		return self.field_of_study

class YearOfStudy(models.Model):
	year_of_study = models.CharField(max_length = 200)
	def __str__(self):
		return self.year_of_study


class Student(models.Model):
	image = models.ImageField(upload_to = 'images/face_datas',unique = True)
	id_n = models.CharField(max_length = 12,unique = True)
	sex = models.CharField(max_length = 1 , choices = sex_choice)

	cafe_status = models.CharField(max_length = 2, choices = cafe_choice)

	dept = models.ForeignKey(Department, on_delete = models.PROTECT)
	field_of_study = models.ForeignKey(FieldOfStudy, on_delete = models.PROTECT)
	year_of_study = models.ForeignKey(YearOfStudy, on_delete = models.PROTECT)
	email = models.EmailField(null = True, blank =True)
	date_of_birth = models.DateField()
	region = models.CharField(max_length = 4, choices = region_choice)


	def __str__(self):
		return self.id_n

users_app/models.py
from django.db import models
from facex.models import Student

from django.contrib.auth.models import AbstractUser



class UserProfile(AbstractUser):
	user = models.OneToOneField(Student, on_delete = models.CASCADE, null = True, blank=True)
	middle_name = models.CharField(max_length = 150, null = True, blank= True)
	phone = models.CharField(max_length = 10, null = True, blank =True)
	profile_picture = models.ImageField(upload_to = 'profile_picture/%y%m%d')

facex/forms.py
from django import forms
from .models import Student, Department, FieldOfStudy , YearOfStudy
from django.contrib.auth import get_user_model
from users_app.models import UserProfile
from django.contrib.auth.forms import UserCreationForm


department_choice = Department.objects.all()
fieldofstudy_choice = FieldOfStudy.objects.all()
yearofstudy_choice = YearOfStudy.objects.all()

User = get_user_model()

class UserPro(UserCreationForm):
	middle_name = forms.CharField(widget =forms.TextInput(
								attrs = {'placeholder':'Middle Name'}),)
	phone = forms.CharField(widget =forms.TextInput(
								attrs = {'placeholder':'Phone'}),max_length = 10)
	class Meta:
		model = User
		fields = ('first_name','last_name','password1','password2')


class StudentForm(forms.ModelForm):

	class Meta:
		model = Student
		fields = ('image','id_n','sex','email',
				  'date_of_birth','region','cafe_status',
				  'year_of_study','field_of_study','dept',)
		widgets = {
			'year_of_study' : forms.Select(choices = yearofstudy_choice, 
										   attrs= {'class':'form-control'}),
			'field_of_study' : forms.Select(choices = 'fieldofstudy_choice'),
			'dept' : forms.Select(choices = 'department_choice'),

		}

users_app/forms.py
from django import forms 
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import UserProfile
from facex.models import Student

User = get_user_model()

'''
class StudentForm(forms.ModelForm):
	class Meta:
		model = Student
		fields = ('image','name','id_n','cafe_status','year_of_study','field_of_study','dept')


class ProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ('user','sex','phone','email','date_of_birth','region','profile_picture')

'''

facex/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from .forms import StudentForm, UserPro
from users_app.models import UserProfile

from django.http import HttpResponse

def my_home(request):
	return render(request, 'index.html', {})


def my_home2(request):
	return render(request, 'index2.html', {})

def my_home3(request):
	return render(request, 'index3.html', {})

def base(request):
	return render(request, 'base.html', {})

def login(request):
	return render(request, 'login.html', {})

def form_view(request):
	return render(request, 'form.html', {})

def index(request):
	return render(request,'home.html', context ={'text':'Hello World'})

def iv(request):
	return HttpResponse('<h2>favicon.ico</h2>')


def setter(form2,profile_form,form1,temp):
	passwd = form2.cleaned_data['password1']
	print(passwd)
	profile_form.set_password(passwd)
	#profile_form.id = form2.cleaned_data['id']
	profile_form.username = form1.cleaned_data['id_n']
	profile_form.first_name = form2.cleaned_data['first_name']
	profile_form.last_name = form2.cleaned_data['last_name']
	profile_form.phone = form2.cleaned_data['phone']
	profile_form.user = temp
	profile_form.profile_picture = form1.cleaned_data['image']
	profile_form.middle_name = form2.cleaned_data['middle_name']
	#form2.profile_picture = form1.cleaned_data['image']
	profile_form.email = form1.cleaned_data['email']
	return profile_form

def register_user(request):
	if request.method == 'POST':
		form1 = StudentForm(request.POST, request.FILES)
		form2 = UserPro(request.POST)
		if form1.is_valid() and form2.is_valid():
			profile_form = UserProfile()
			temp = form1.save(commit = False)
			profile_form = setter(form2,profile_form,form1,temp)
			form1.save(commit = True)
			profile_form.save()
			print("Successfully wiped")
			return redirect('facex:register')
		else:
			print('not Successfully reged')			
			
	else:
		form2 = UserPro()
		form1 = StudentForm()

	context = {'form1':form1,'form2':form2}
	return render(request, 'student_management/register.html',context)

users_app/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView
#from .forms import ProfileForm
#from facex.models import Student 

from django.http import HttpResponse

User = get_user_model()


def home(request):
	return HttpResponse('<b>Hello World</b>')

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>AdminLTE 3 | Dashboard 3</title>

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'admin-lte/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- IonIcons -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'admin-lte/dist/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="{% url 'facex:my_home' %}" class="nav-link">Home</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="#" class="nav-link">Contact</a>
                </li>
            </ul>

            <!-- SEARCH FORM -->
            <form class="form-inline ml-3">
                <div class="input-group input-group-sm">
                    <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                    <div class="input-group-append">
                        <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
                    </div>
                </div>
            </form>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- Notifications Dropdown Menu -->
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="far fa-bell"></i>
                        <span class="badge badge-warning navbar-badge">15</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <span class="dropdown-item dropdown-header">15 Notifications</span>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-envelope mr-2"></i> 4 new messages
                            <span class="float-right text-muted text-sm">3 mins</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-users mr-2"></i> 8 friend requests
                            <span class="float-right text-muted text-sm">12 hours</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-file mr-2"></i> 3 new reports
                            <span class="float-right text-muted text-sm">2 days</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button"><i
            class="fas fa-th-large"></i></a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4" style="height:100vh;">
            <!-- Brand Logo -->
            <a href="index3.html" class="brand-link">
                <img src="{% static 'admin-lte/dist/img/prod-1.jpg' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">ASTU</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="{% static 'admin-lte/dist/img/avatar.png' %}" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">{{ request.user }}</a>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
                        <li class="nav-item has-treeview menu-open">
                            <a href="{% url 'facex:my_home' %}" class="nav-link active">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Dashboard
                                </p>
                            </a>

                        </li>
                        <li class="nav-item">
                            <a href="{% url 'facex:form' %}" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    Form
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon far fa-envelope"></i>
                                <p>
                                    Reports
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon far fa-plus-square"></i>
                                <p>
                                    Profile
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="{% url 'facex:login' %}" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Login</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/examples/login.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Edit Profile</p>
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a href="pages/examples/forgot-password.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Change Password</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/examples/language-menu.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Logout</p>
                                    </a>
                                </li>

                            </ul>
                        </li>

                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->

        <!-- Content Header (Page header) -->

        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">{% if title %} {{ title }} {% endif %}</h1>
                    </div>
                    <!-- /.col -->
                    {% comment %}
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Dashboard v3</li>
                        </ol>
                    </div> {% endcomment %}
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
        {% block content %}{% endblock content %}
        <!-- Main Footer -->
        <footer class="main-footer" style="bottom:0;">
            <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 3.0.4
            </div>
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->

    <!-- jQuery -->
    <script src="{% static 'admin-lte/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE -->
    <script src="{% static 'admin-lte/dist/js/adminlte.js' %}"></script>

    <!-- OPTIONAL SCRIPTS -->
    <script src="{% static 'admin-lte/dist/js/demo.js' %}"></script>
    <script src="{% static 'admin-lte/dist/js/pages/dashboard.js' %}"></script>
</body>

</html>

templates/form.html
{% extends "base.html" %} {% block content %}
<!-- Content Wrapper. Contains page content -->
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="container col-md-6">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Quick Example</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form role="form">
                        <div class="card-body">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Email address</label>
                                <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Password</label>
                                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputFile">File input</label>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="exampleInputFile">
                                        <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                                    </div>
                                    <div class="input-group-append">
                                        <span class="input-group-text" id="">Upload</span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <!-- select -->
                                <div class="form-group">
                                    <label>Select</label>
                                    <select class="form-control">
                                                <option>option 1</option>
                                                <option>option 2</option>
                                                <option>option 3</option>
                                                <option>option 4</option>
                                                <option>option 5</option>
                                        </select>
                                </div>
                            </div>
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                                <label class="form-check-label" for="exampleCheck1">Check me out</label>
                            </div>
                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
                <!-- /.card -->

            </div>
            <!--/.col (left) -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->
{% endblock content %}

templates/home.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Index</title>
</head>
<body>
	<div id='img'></div>
	<h2 id='name'>{{text}}</h2> 
	<h3 id='id'></h3>
	<h3 id='dept'></h3>
	

	<script>
		
		var socket = new WebSocket('ws://localhost:8000/ws/some_url/');
		
		socket.onmessage = function(event)
		{
			 var data = JSON.parse(event.data);
			 console.log(data);
			 if (data.message != "Unknown face detected")
			 {   
			 	 
			 	 document.querySelector('#name').innerText = data.name;
				 document.querySelector('#id').innerText = data.id;
				 document.querySelector('#dept').innerText = data.Department;
				 //document.querySelector('#img').innerText = data.img;
				 var el = document.getElementById("img");
   				 el.innerHTML=`<img src= ${data.img}>`;
   				 //alert(`${window.location.origin}{{ data.img }}`)
   				 //alert(data.img)

			}	

			else 
			{
				document.querySelector('#name').innerText = data.message;	
				document.querySelector('#id').innerText = ''
				document.querySelector('#dept').innerText = ''
				document.querySelector('#img').innerText = ''

			}
		}	

	</script>

</body>



</html>

templates/login.html
{% extends "base.html" %} {% block content %}
<div class="container login-box">
    <div class="login-logo">
        <a href="../../index2.html"><b>Admin</b>LTE</a>
    </div>
    <!-- /.login-logo -->
    <div class="card">
        <div class="card-body login-card-body">
            <p class="login-box-msg">Sign in to start your session</p>

            <form action="../../index3.html" method="post">
                <div class="input-group mb-3">
                    <input type="email" class="form-control" placeholder="Email">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="password" class="form-control" placeholder="Password">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-8">
                        <div class="icheck-primary">
                            <input type="checkbox" id="remember">
                            <label for="remember">
                Remember Me
              </label>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block">Sign In</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>

            <div class="social-auth-links text-center mb-3">
                <p>- OR -</p>
                <a href="#" class="btn btn-block btn-primary">
                    <i class="fab fa-facebook mr-2"></i> Sign in using Facebook
                </a>
                <a href="#" class="btn btn-block btn-danger">
                    <i class="fab fa-google-plus mr-2"></i> Sign in using Google+
                </a>
            </div>
        </div>
    </div>
    <!-- <div class="card" style="height: 10em;"></div> -->
</div>
<!-- /.social-auth-links -->
{% endblock content %}

templates/logs/log.html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>HTML Logger</title>
<style type="text/css">
body, html {
background: #000000;
width: auto;
font-family: Arial;
font-size: 16px;
color: #C0C0C0;
}
h1 {
color : #FFFFFF;
border-bottom : 1px dotted #888888;
}
.box {
border : 1px dotted #818286;
padding : 5px;
margin: 5px;
width: auto;
background-color : #292929;
}
.err {
word-break:break-all; word-wrap:break-all;
color: red;
font-family : arial;
margin : 0;
}
.warn {
word-break:break-all; word-wrap:break-all;
color: red;
font-family : arial;
margin : 0;

}
.info {
word-break:break-all; word-wrap:break-all;
color: white;
font-family : arial;
margin : 0;
}
.debug {
word-break:break-all; word-wrap:break-all;
color: white;
font-family : arial;
margin : 0;
}
</style>
</head>
<body>
<h1>HTML Log</h1>

<p>Select a category to display:
<select id="mySelect" onchange="cate_fun()">
  <option value="ALL">ALL
  <option value="DEBUG">DEBUG
  <option value="INFO">INFO
  <option value="WARNING">WARNING
  <option value="ERROR">ERROR
</select> 
</p>

<form>
Type Keyword to display:
<input type="text" id="text1" value="ALL" size="12"/>
<input type="checkbox" id="check1" />
<input type="button" id="button1" onclick="keyword_fun()" 
value="Seach" />
</form>

<script>
var level_index = 3
var msg_index = 4
function cate_fun(){
var tab = document.getElementById("toptable");
var slct_v = document.getElementById("mySelect").value;

for(var i=0; i<tab.rows.length;i++)
{
  	if (tab.rows[i].cells[level_index].innerHTML=="DEBUG" & slct_v=="DEBUG")
    {
	    tab.rows[i].style.display='';
	}
	else if (tab.rows[i].cells[level_index].innerHTML=="INFO" & slct_v=="INFO")
    {
	    //console.log(i)
		//console.log(tab.rows[i].cells[level_index].innerHTML)
	    tab.rows[i].style.display='';
	}
	else if (tab.rows[i].cells[level_index].innerHTML=="TABLE" & slct_v=="INFO")
    {
	    tab.rows[i].style.display='';
	}
	else if (tab.rows[i].cells[level_index].innerHTML=="WARNING" & slct_v=="WARNING")
    {
	    tab.rows[i].style.display='';
	}
	else if (tab.rows[i].cells[level_index].innerHTML=="ERROR" & slct_v=="ERROR")
    {
	    tab.rows[i].style.display='';
	}
	else
	{
		if (slct_v=="ALL"){
			tab.rows[i].style.display='';
		}
		else{
			tab.rows[i].style.display='none';
		};
	};
}
}

function keyword_fun()
{
var tab = document.getElementById("toptable");
var Keyword = document.getElementById("text1").value;
if (document.getElementById("check1").checked)
	{
	    Keyword=Keyword.toLowerCase();
	}
for (var i=0;i<tab.rows.length;i++) {
	if (Keyword=="ALL" || Keyword=="all")
	{
		tab.rows[i].style.display='';
	}
	else
	{
		var td_msg=tab.rows[i].cells[msg_index].innerHTML
		if (document.getElementById("check1").checked)
			{
			    td_msg=td_msg.toLowerCase();
			}
		if (td_msg.indexOf(Keyword)>=0)
			{
			    //console.log(Keyword)
			    tab.rows[i].style.display='';
			}
		else
			{
				//console.log(i)
			    tab.rows[i].style.display='none';
			};
    };  
  };
}

</script>

<div class="box">
<table id="toptable">
</table>
</div>
</body>
</html>

templates/student_management/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>
		{%block title %}
		{% endblock title %}
	</title>
	<link rel="stylesheet" href="">
</head>
<body>
	<div>
	<a href="{% url 'home'%}" title="" style ="text-decoration: none; color: black"><h1>Authentication</h1></a>
</div>
	<div style = "padding-left: 30px; padding-top: 5px">
	{% if user.is_authenticated%}

		<a href="{% url 'logout'%}" title="" >logout</a>
		{% block edit %}

		{% endblock edit%}

		{% block change %}

		{% endblock change%}


	{% if user.is_staff %}
		<a href="{% url 'admin:index' %}">Admin Page</a>
		<a href="{% url 'index' %}">Active camera</a>
	{%endif%}
	{% if user.is_superuser %}
		{% block link %}			
		{% endblock link %}
	{%endif%}
	{%endif%}
	<br>
	{%block content%}
	{%endblock%}

	{% block index %}
		
	{% endblock index %}


	
</div>

</body>
</html>

templates/student_management/change_password.html
{% extends 'student_management/base.html'%}


{%block title %}
	Change Password
{% endblock title %}

{% block edit %}
<a href="{% url 'edit_profile'%}" title="" >Edit Profile</a>
{% endblock edit %}
{%block content%}
	
	<form action="{% url 'change_password' %}" method="POST" accept-charset="utf-8">
	{% csrf_token%}
	{% if form.errors %}

		<p>Your form has errors...</p>
		{% for field in form %}
		{% if field.error %}
			{{ field }}
		{% endif %}
		{% endfor %}

	{% endif %}


	{{ form.as_p }}
<input type="submit" name="" value="Update" >
	</form>
		
{% endblock %}

templates/student_management/edit_profile.html
{% extends 'student_management/base.html'%}


{%block title %}
	Edit Profile
{% endblock title %}


{%block change%}
	 <h2 >Edit Profile</h2>
<form action="{% url 'edit_profile'%}" method="POST" accept-charset="utf-8" enctype="multipart/form-data">
	{% csrf_token%}
	{% if form.errors %}

		<p>Your form has errors...</p>
		{% for field in form%}
		{%if field.error%}
			{{ field }}
		{%endif%}
		{% endfor %}

	{% endif %}


	{{ form.as_p }}
	<p><small><a href="{% url 'change_password'%}">Click here </a>to change your password.</small></p>
<input type="Submit"  value="Update" >
</form>

{% endblock %}

templates/student_management/home.html
{% extends 'student_management/base.html'%}


{%block title %}
	Home page
{% endblock title %}

{% block index %}
<h1>Welcome Home papa</h1>

{% if perms.facex.add_userprofile %}
	<a href="{% url 'sign' %}">Register Users</a>
{% endif %}

<a href="{% url 'edit_profile' %}"> Edit Profile </a>
{% endblock index %}

templates/student_management/login.html
{% extends 'student_management/base.html'%}


{%block title %}
	Login
{% endblock title %}

{% block link %}
	<a href="{% url 'register' %}" title="">Register</a>
{% endblock link %}

{%block content%}
<body>
	<div>
		<form method="POST" accept-charset="utf-8">
			{% csrf_token%}

			<input type="text" name="username" placeholder="User Name"><br>
			<input type="password" name="password" placeholder="Password">
			<br>
			<button type="submit">Login</button>
		</form>
	</div>

</body>
</html>
{% endblock content%}